version: "3.9"

services:
  backend:
    build:
      context: ./mybackend
      dockerfile: Dockerfile
    container_name: django_backend
    ports:
      - "8000:8000"
    volumes:
      - ./mybackend:/app
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: angular_frontend
    ports:
      - "4200:80"
    depends_on:
      - backend
    restart: unless-stopped